/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CategoryItem { 'name' : string, 'defaultPrice' : number }
export interface DailyEntry {
  'morning' : ShiftEntry,
  'evening' : ShiftEntry,
  'date' : string,
}
export interface EntryWithTotals {
  'morning' : ShiftEntry,
  'evening' : ShiftEntry,
  'totalPurchase' : number,
  'date' : string,
  'profitLoss' : number,
  'totalSale' : number,
  'totalExpense' : number,
}
export interface Item {
  'outlet' : string,
  'description' : string,
  'amount' : number,
}
export interface SaleItem {
  'freeQuantity' : bigint,
  'name' : string,
  'quantity' : bigint,
  'amount' : number,
}
export interface ShiftEntry {
  'expenses' : Array<Item>,
  'sales' : Array<SaleItem>,
  'purchases' : Array<Item>,
}
export interface _SERVICE {
  'addExpenseCategoryWithPrice' : ActorMethod<[string, number], undefined>,
  'addPurchaseCategoryWithPrice' : ActorMethod<[string, number], undefined>,
  'addSaleCategoryWithPrice' : ActorMethod<[string, number], undefined>,
  'deleteExpenseCategoryWithPrice' : ActorMethod<[string], undefined>,
  'deletePurchaseCategoryWithPrice' : ActorMethod<[string], undefined>,
  'deleteSaleCategoryWithPrice' : ActorMethod<[string], undefined>,
  'getAllEntries' : ActorMethod<[], Array<DailyEntry>>,
  'getEntriesByMonth' : ActorMethod<[string, string], Array<DailyEntry>>,
  'getEntriesByYear' : ActorMethod<[string], Array<DailyEntry>>,
  'getEntryByDate' : ActorMethod<[string], [] | [EntryWithTotals]>,
  'getExpenseCategoriesWithPrice' : ActorMethod<[], Array<CategoryItem>>,
  'getPurchaseCategoriesWithPrice' : ActorMethod<[], Array<CategoryItem>>,
  'getSaleCategoriesWithPrice' : ActorMethod<[], Array<CategoryItem>>,
  'saveEntries' : ActorMethod<[Array<DailyEntry>], undefined>,
  'saveEntry' : ActorMethod<[DailyEntry], undefined>,
  'updateExpenseCategoryPrice' : ActorMethod<[string, number], undefined>,
  'updatePurchaseCategoryPrice' : ActorMethod<[string, number], undefined>,
  'updateSaleCategoryPrice' : ActorMethod<[string, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];