/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Item = IDL.Record({
  'outlet' : IDL.Text,
  'description' : IDL.Text,
  'amount' : IDL.Float64,
});
export const SaleItem = IDL.Record({
  'freeQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'amount' : IDL.Float64,
});
export const ShiftEntry = IDL.Record({
  'expenses' : IDL.Vec(Item),
  'sales' : IDL.Vec(SaleItem),
  'purchases' : IDL.Vec(Item),
});
export const DailyEntry = IDL.Record({
  'morning' : ShiftEntry,
  'evening' : ShiftEntry,
  'date' : IDL.Text,
});
export const EntryWithTotals = IDL.Record({
  'morning' : ShiftEntry,
  'evening' : ShiftEntry,
  'totalPurchase' : IDL.Float64,
  'date' : IDL.Text,
  'profitLoss' : IDL.Float64,
  'totalSale' : IDL.Float64,
  'totalExpense' : IDL.Float64,
});
export const CategoryItem = IDL.Record({
  'name' : IDL.Text,
  'defaultPrice' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addExpenseCategoryWithPrice' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'addPurchaseCategoryWithPrice' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'addSaleCategoryWithPrice' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'deleteExpenseCategoryWithPrice' : IDL.Func([IDL.Text], [], []),
  'deletePurchaseCategoryWithPrice' : IDL.Func([IDL.Text], [], []),
  'deleteSaleCategoryWithPrice' : IDL.Func([IDL.Text], [], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(DailyEntry)], ['query']),
  'getEntriesByMonth' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(DailyEntry)],
      ['query'],
    ),
  'getEntriesByYear' : IDL.Func([IDL.Text], [IDL.Vec(DailyEntry)], ['query']),
  'getEntryByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(EntryWithTotals)],
      ['query'],
    ),
  'getExpenseCategoriesWithPrice' : IDL.Func(
      [],
      [IDL.Vec(CategoryItem)],
      ['query'],
    ),
  'getPurchaseCategoriesWithPrice' : IDL.Func(
      [],
      [IDL.Vec(CategoryItem)],
      ['query'],
    ),
  'getSaleCategoriesWithPrice' : IDL.Func(
      [],
      [IDL.Vec(CategoryItem)],
      ['query'],
    ),
  'saveEntries' : IDL.Func([IDL.Vec(DailyEntry)], [], []),
  'saveEntry' : IDL.Func([DailyEntry], [], []),
  'updateExpenseCategoryPrice' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'updatePurchaseCategoryPrice' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'updateSaleCategoryPrice' : IDL.Func([IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Item = IDL.Record({
    'outlet' : IDL.Text,
    'description' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const SaleItem = IDL.Record({
    'freeQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  const ShiftEntry = IDL.Record({
    'expenses' : IDL.Vec(Item),
    'sales' : IDL.Vec(SaleItem),
    'purchases' : IDL.Vec(Item),
  });
  const DailyEntry = IDL.Record({
    'morning' : ShiftEntry,
    'evening' : ShiftEntry,
    'date' : IDL.Text,
  });
  const EntryWithTotals = IDL.Record({
    'morning' : ShiftEntry,
    'evening' : ShiftEntry,
    'totalPurchase' : IDL.Float64,
    'date' : IDL.Text,
    'profitLoss' : IDL.Float64,
    'totalSale' : IDL.Float64,
    'totalExpense' : IDL.Float64,
  });
  const CategoryItem = IDL.Record({
    'name' : IDL.Text,
    'defaultPrice' : IDL.Float64,
  });
  
  return IDL.Service({
    'addExpenseCategoryWithPrice' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'addPurchaseCategoryWithPrice' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'addSaleCategoryWithPrice' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'deleteExpenseCategoryWithPrice' : IDL.Func([IDL.Text], [], []),
    'deletePurchaseCategoryWithPrice' : IDL.Func([IDL.Text], [], []),
    'deleteSaleCategoryWithPrice' : IDL.Func([IDL.Text], [], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(DailyEntry)], ['query']),
    'getEntriesByMonth' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(DailyEntry)],
        ['query'],
      ),
    'getEntriesByYear' : IDL.Func([IDL.Text], [IDL.Vec(DailyEntry)], ['query']),
    'getEntryByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(EntryWithTotals)],
        ['query'],
      ),
    'getExpenseCategoriesWithPrice' : IDL.Func(
        [],
        [IDL.Vec(CategoryItem)],
        ['query'],
      ),
    'getPurchaseCategoriesWithPrice' : IDL.Func(
        [],
        [IDL.Vec(CategoryItem)],
        ['query'],
      ),
    'getSaleCategoriesWithPrice' : IDL.Func(
        [],
        [IDL.Vec(CategoryItem)],
        ['query'],
      ),
    'saveEntries' : IDL.Func([IDL.Vec(DailyEntry)], [], []),
    'saveEntry' : IDL.Func([DailyEntry], [], []),
    'updateExpenseCategoryPrice' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'updatePurchaseCategoryPrice' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'updateSaleCategoryPrice' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };