/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DailyEntry {
    rajajiSale: number;
    date: string;
    expenses: Array<Item>;
    purchases: Array<Item>;
    saroorpurSale: number;
    oldRaoSale: number;
}
export interface Item {
    outlet: string;
    description: string;
    amount: number;
}
export interface CategoryItem {
    name: string;
    defaultPrice: number;
}
export interface EntryWithTotals {
    rajajiSale: number;
    totalPurchase: number;
    date: string;
    expenses: Array<Item>;
    profitLoss: number;
    totalSale: number;
    purchases: Array<Item>;
    saroorpurSale: number;
    totalExpense: number;
    oldRaoSale: number;
}
export interface backendInterface {
    addExpenseCategoryWithPrice(name: string, defaultPrice: number): Promise<void>;
    addPurchaseCategoryWithPrice(name: string, defaultPrice: number): Promise<void>;
    deleteExpenseCategoryWithPrice(name: string): Promise<void>;
    deletePurchaseCategoryWithPrice(name: string): Promise<void>;
    getAllEntries(): Promise<Array<DailyEntry>>;
    getEntriesByMonth(year: string, month: string): Promise<Array<DailyEntry>>;
    getEntriesByYear(year: string): Promise<Array<DailyEntry>>;
    getEntryByDate(date: string): Promise<EntryWithTotals | null>;
    getExpenseCategoriesWithPrice(): Promise<Array<CategoryItem>>;
    getPurchaseCategoriesWithPrice(): Promise<Array<CategoryItem>>;
    saveEntries(entryArray: Array<DailyEntry>): Promise<void>;
    saveEntry(entry: DailyEntry): Promise<void>;
    updateExpenseCategoryPrice(name: string, newPrice: number): Promise<void>;
    updatePurchaseCategoryPrice(name: string, newPrice: number): Promise<void>;
}
import type { EntryWithTotals as _EntryWithTotals } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addExpenseCategoryWithPrice(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpenseCategoryWithPrice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpenseCategoryWithPrice(arg0, arg1);
            return result;
        }
    }
    async addPurchaseCategoryWithPrice(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPurchaseCategoryWithPrice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPurchaseCategoryWithPrice(arg0, arg1);
            return result;
        }
    }
    async deleteExpenseCategoryWithPrice(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpenseCategoryWithPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpenseCategoryWithPrice(arg0);
            return result;
        }
    }
    async deletePurchaseCategoryWithPrice(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePurchaseCategoryWithPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePurchaseCategoryWithPrice(arg0);
            return result;
        }
    }
    async getAllEntries(): Promise<Array<DailyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEntries();
            return result;
        }
    }
    async getEntriesByMonth(arg0: string, arg1: string): Promise<Array<DailyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntriesByMonth(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntriesByMonth(arg0, arg1);
            return result;
        }
    }
    async getEntriesByYear(arg0: string): Promise<Array<DailyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntriesByYear(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntriesByYear(arg0);
            return result;
        }
    }
    async getEntryByDate(arg0: string): Promise<EntryWithTotals | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntryByDate(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntryByDate(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpenseCategoriesWithPrice(): Promise<Array<CategoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenseCategoriesWithPrice();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenseCategoriesWithPrice();
            return result;
        }
    }
    async getPurchaseCategoriesWithPrice(): Promise<Array<CategoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchaseCategoriesWithPrice();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchaseCategoriesWithPrice();
            return result;
        }
    }
    async saveEntries(arg0: Array<DailyEntry>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEntries(arg0);
            return result;
        }
    }
    async saveEntry(arg0: DailyEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEntry(arg0);
            return result;
        }
    }
    async updateExpenseCategoryPrice(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpenseCategoryPrice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpenseCategoryPrice(arg0, arg1);
            return result;
        }
    }
    async updatePurchaseCategoryPrice(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePurchaseCategoryPrice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePurchaseCategoryPrice(arg0, arg1);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EntryWithTotals]): EntryWithTotals | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
